-- 필요 시 테이블 제거
DROP TABLE team_member PURGE;

-- 테이블 생성
-- 회원 테이블
CREATE TABLE final_member (
    num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,		-- 회원번호
    id VARCHAR2(30) UNIQUE NOT NULL,										-- 회원 아이디
    pass VARCHAR2(30) NOT NULL,												-- 비밀번호
    name VARCHAR2(50),														-- 회원이름
    nickname VARCHAR2(30) UNIQUE NOT NULL,									-- 닉네임
    phone VARCHAR2(20),														-- 전화번호
    email VARCHAR2(50),														-- 이메일
    gender VARCHAR2(10),													-- 성별(남성,여성)
    age NUMBER(3)															-- 나이
);

-- 영화 테이블
CREATE TABLE final_movie (
	movie_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 	-- 영화 코드
	title VARCHAR2(150) NOT NULL,												-- 영화 제목
	director VARCHAR2(30) NOT NULL,												-- 감독명
	genre VARCHAR2(50),															-- 장르
	release_date DATE NOT NULL,													-- 개봉일
	age_limit NUMBER(3),														-- 관람연령제한
	story CLOB,																	-- 줄거리
	running_time NUMBER NOT NULL												-- 상영시간(분단위)
	-- 포스터 이미지
);

-- 댓글 테이블
CREATE TABLE movie_comment(
	comment_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 	-- 댓글 번호
	member_id VARCHAR2(30) NOT NULL REFERENCES final_member(id),			-- 회원 아이디
	movie_code NUMBER NOT NULL REFERENCES final_movie(movie_code), 				-- 영화 코드
	content CLOB,																-- 댓글 내용
	score NUMBER NOT NULL,														-- 별점					
	reg_date DATE DEFAULT SYSDATE,												-- 게시 날짜
	update_date DATE															-- 수정 날짜
);

-- 영화관 종류(메가박스, CGV 등)
CREATE TABLE theater(
	theater_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 영화관 코드
	theater_name VARCHAR2(20)													-- 영화관 이름
);

-- 영화관 지점 테이블
CREATE TABLE theater_branch(
	theater_code NUMBER NOT NULL REFERENCES theater(theater_code),				-- 영화관 코드	
	branch_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 지점 코드
	branch_name VARCHAR2(30) NOT NULL,											-- 지점명
	addr VARCHAR2(150) NOT NULL,												-- 주소
	phone VARCHAR2(30)															-- 연락처
);

-- 지점별 상영관 테이블
CREATE TABLE branch_screen(
	branch_code NUMBER NOT NULL REFERENCES theater_branch(branch_code),			-- 지점 코드
	screen_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 상영관 코드
	screen_name VARCHAR2(30) NOT NULL,											-- 상영관 이름(1관 2관 등)
	screen_type VARCHAR2(30) NOT NULL											-- 상영관 종류(2D, 돌비 등)
);

CREATE TABLE schedule (
	schedule_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	movie_code NUMBER NOT NULL REFERENCES final_movie(movie_code),
	screen_code NUMBER NOT NULL REFERENCES branch_screen(screen_code),
	start_time DATE NOT NULL,
	end_time date
);

ALTER TABLE final_movie ADD poster VARCHAR2(300);

SELECT * FROM final_movie;
SELECT * FROM final_member;

--기존 칼럼 삭제 sql
ALTER TABLE final_movie DROP COLUMN poster;
-- VARCHAR2(300)을 추가하기 전에 CLOB으로 추가하던지 아니면 poster 칼럼을 삭제 후 추가
ALTER TABLE final_movie ADD poster CLOB;


-- 데이터 삽입 (테이블 생성 후 관리자 계정 추가)
INSERT INTO team_member (
    id, pass, name, addr, phone, email, gender, age
) VALUES (
    'admin', 'admin', 'MASTER',
    '부산광역시', '01011111111', 'lkjnibnhjunjh','남성', 30
);

-- 수정
UPDATE team_member 
SET email = 'new_email@example.com'  -- 임시로 넣을 이메일
WHERE id = 'admin';

-- 조회
SELECT * FROM team_member;

-- 커밋
COMMIT


-- ===========================================
-- test_member 테이블에 더미 테이블 추가
-- test_member table 에서 검색 된 결과를
-- test_member 테이블에 그대로 입력
-- id column UNIQUE
-- ORA-00001: 무결성 제약 조건(DEVELOP_JSP.SYS_C008346)에 위배됩니다
-- ===========================================

INSERT INTO team_member(id, pass, name, addr, phone, gender, age)
SELECT id, pass, name, addr, phone, gender, age FROM test_member;

-- ===========================================
-- test_member 테이블에 더미 데이터 10,000건 생성
-- CONNECT BY LEVEL 을 이용한 Oracle 계층 쿼리 활용
-- ===========================================

-- ORA-01722: 수치가 부적합합니다
-- + 연상은 산술(수치형) 연산에서만 사용
SELECT 'a' + 'b' FROM DUAL;

-- 30
SELECT 10 + 20 FROM DUAL;

-- concatenate : 연결하다
-- 'ab'
SELECT concat('a', 'b') FROM DUAL;

-- CONCAT 함수는 인자값 두개만 가능
-- ORA-00909: 인수의 개수가 부적합합니다
-- SELECT concat('a', 'b', 'c') FROM DUAL;
-- 'abc'
SELECT CONCAT(CONCAT('a', 'b'), 'c') FROM DUAL;

-- 'abcd'
SELECT 'a' || 'b' || 'c' || 'd' FROM DUAL;


SELECT
	CASE
		WHEN MOD(3, 2) = 1
			THEN '부산'
			ELSE '서울'
	END		
FROM DUAL;

-- TRUNC() : TRUNCATE : 잘라내다
-- 소수점이나 시간 등을 잘라내는 함수(반올림,내림,올림 아님 : 제거)
SELECT TRUNC(DBMS_RANDOM.VALUE(20, 70)) FROM DUAL;

-- CONNECT BY LEVEL <= 40
-- 1부터 40까지의 자동 증가 숫자 생성
-- SELECT LEVEL FROM DUAL : LEVEL => 계츨 쿼리에서 자동 증하가는 가상 컬럼

SELECT 
	LEVEL
FROM DUAL
CONNECT BY LEVEL <= 40;


-- ============================================

INSERT INTO team_member(id, pass, name, addr, phone, gender, age)
SELECT
	-- user1, user2, user3 ... user10000
	'user' || LEVEL AS id,
	
	-- pass1, pass2, pass3 ... pass10000
	'pass' || LEVEL AS pass,
	
	-- 사용자1, 사용자2, 사용자3 ... 사용자10000
	'사용자' || LEVEL AS name,
	
	CASE WHEN MOD(LEVEL, 2) = 1 THEN '부산' ELSE '서울' END AS addr,
	'01012345678' AS phone,
	CASE WHEN MOD(LEVEL, 2) = 1 THEN '남성' ELSE '여성' END AS gender,
	
	-- 나이 (20 ~ 70세 랜덤)
	TRUNC(DBMS_RANDOM.VALUE(20, 70)) AS age
	
FROM DUAL
CONNECT BY LEVEL <= 10000;

----------------------------------------------------

SELECT count(*) FROM team_member;

COMMIT

-- ============================================
-- 키워드 검색
-- ?searchType=addr&keyword=부산&perPageNum=15
-- ============================================

SELECT * FROM team_member
WHERE id != 'admin' AND addr LIKE '%' || '부산' || '%'
ORDER BY num DESC
OFFSET 0 ROWS FETCH NEXT 25 ROWS ONLY;

-----------------------------------------------------------------------

SELECT count(*) FROM team_member
WHERE id != 'admin' AND addr LIKE '%'||'부산'||'%';
-- WHERE id != 'admin' AND id LIKE '%'||'id'||'%'; -- 0

-- 사용자 이메일 정보 저장을 위찬 column 추가
ALTER TABLE team_member ADD email VARCHAR2(300);

-- 기존 데이터에 DUMMY 이메일 정보 추가
UPDATE team_member
SET email = id || '@gmail.com'
WHERE email IS NULL;

-- NOT NULL 제약 조건 추가 - email 은 비밀번호를 찾기 위한 필수 데이터
ALTER TABLE team_member MODIFY email VARCHAR2(300) NOT NULL;

-- 회원 정보 조회
SELECT * FROM team_member;

-- 게시판 조회
SELECT * FROM board_team;

-- 게시판 더미데이터 삭제
DELETE FROM board_team;

-- 저장
COMMIT

-- 시퀀스 존재 여부 판단
SELECT * FROM user_sequences WHERE sequence_name = 'BOARD_SEQ';



INSERT INTO board_team(title, author, content, category)
SELECT title, author, content, category
FROM board_team
WHERE category = 'NOTICE';

--필요 시 영화 db 삭제--
DROP TABLE final_movie CASCADE CONSTRAINTS PURGE;

--영화 db 조회--
SELECT * FROM final_movie;

--영화 db 최신 개봉일 순으로 조회
SELECT * FROM final_movie ORDER BY release_date DESC;

--영화 db 포스터 이미지 경로만 수정하는 sql--
UPDATE final_movie 

SET poster = '/resources/img/movies/we_live_in_time.jpg' -- 예시)'/resources/img/movies/we_live_in_time.jpg'



WHERE title = '위 리브 인 타임';

--영화 db등록--
INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '위 리브 인 타임', 
    '존 크로울리', 
    '멜로/로맨스, 드라마', 
    '2026-04-08', 
    15,
    '본인의 레스토랑 오픈을 준비하며 새로운 도약을 꿈꾸는 셰프 ‘알무트’. 
	최근 이혼을 하면서 삶의 한 챕터를 끝낸 ‘토비아스’. 예기치 못한 만남을 계기로 두 사람은 서로의 삶을 변화시키는 잊지 못할 10년을 보낸다. 
	우리의 사랑은 함께한 시간에 영원히 남는다.',
    108,
    '/resources/img/movies/we_live_in_time.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '기동전사 건담 철혈의 오펀스 우르드 헌트', 
    '나가이 타츠유키', 
    'sf', 
    '2026-04-04', 
    12,
    '“축하드립니다. 당신은 ‘우르드 헌트’의 참가 자격을 얻었습니다.” 
    화성과의 개척 경쟁에서 패배하고 죄인들의 유배지로 전락한 변방 행성, 
    금성. 그곳의 라도니차 콜로니에서 나고 자란 소년 위스타리오 아팜은 척박한 고향의 현실을 바꾸고 싶다는 열망을 품고 살아간다.',
    78,
    '/resources/img/movies/gundam.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '런닝맨 라이트&쉐도우', 
    '윤준상', 
    '?', 
    '2026-04-11', 
    0,
    '세상을 지키던 히어로가 다크 런닝맨이 되었다?! 수차례에 걸쳐 세상을 구한 런닝맨들은 트리시티의 대스타로 절대적인 지지를 받고 있다. 
    그러던 어느 날 런닝맨들이 돌연 위험한 악당이 되어 시민들을 공격하기 시작하는데… ',
    81,
    '/resources/img/movies/runningman.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '로마의 휴일', 
    '윌리엄 와일러', 
    '멜로/로맨스, 드라마, 코미디', 
    '2026-04-08', 
    12,
    '유럽 순방 중 로마를 방문한 공주 ‘앤’. 
    끝없는 일정에 지쳐버린 그녀는 한밤중 몰래 침실을 빠져나와 처음으로 자유롭게 로마의 거리를 거닌다.',
    118,
    '/resources/img/movies/roman_holiday.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '티파니에서 아침을', 
    '블레이크 에드워즈', 
    '멜로/로맨스,드라마', 
    '2026-04-08', 
    12,
    '뉴욕 맨해튼에서 자유로운 삶을 살아가는 여성 ‘홀리 골라이틀리’(오드리 헵번)는 화려한 사교 생활을 즐기며 부유한 삶을 동경한다.',
    115,
    '/resources/img/movies/tiffanys.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '리바운드', 
    '장항준', 
    '드라마', 
    '2026-04-05', 
    12,
    '농구선수 출신 공익근무요원 양현은 해체 위기에 놓인 부산중앙고 농구부의 신임 코치로 발탁된다.',
    122,
    '/resources/img/movies/rebound.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '리바운드', 
    '장항준', 
    '드라마', 
    '2026-04-05', 
    12,
    '농구선수 출신 공익근무요원 양현은 해체 위기에 놓인 부산중앙고 농구부의 신임 코치로 발탁된다.',
    122,
    '/resources/img/movies/rebound.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '크라임101', 
    '바트 레이튼', 
    '범죄,드라마,스릴러', 
    '2026-04-08', 
    12,
    '흔적도, 증거도 없다! 101번 국도를 따라 흔적도 없이 사라지는 보석들. 전설적인 절도범 ‘데이비스’(크리스 헴스워스)는 자신만의 규칙 아래 완벽한 범죄를 설계한다.',
    140,
    '/resources/img/movies/Crime_101.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '살목지', 
    '이상민', 
    '공포,스릴러', 
    '2026-04-08', 
    15,
    '기이한 소문이 끊이지 않는 저수지 살목지의 로드뷰 화면에 촬영한 적 없는 정체불명의 형체가 포착된다.
     오늘 안에 반드시 재촬영을 끝내야 하는 상황 속에 살목지로 향한 PD ‘수인’(김혜윤)과 촬영팀.',
    140,
    '/resources/img/movies/Whispering_Water.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '그대들은 어떻게 살것인가', 
    '미야자키 하야오', 
    '다큐멘터리', 
    '2026-04-15', 
    12,
    '인생이 담긴 마지막 작품을 완성하기 위한 미야자키 하야오의 고뇌와 갈등, 긴 세월을 함께한 동료들과 예기치 못한 이별까지…',
    120,
    '/resources/img/movies/Hayao_Miyzaki_and_the_Heron.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '하이큐 쓰레기장의 결전', 
    '미츠나가 스스무', 
    '스포츠', 
    '2026-04-15', 
    0,
    '봄철 고교 배구대회 1회전과 2회전에서 우승 후보를 차례로 꺾은 카라스노 고등학교는 마침내 3회전에서 인연의 라이벌 네코마 고등학교와 맞붙게 된다.',
    85,
    '/resources/img/movies/High_Q.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '마녀 배달부 키키', 
    '미야자키 하야오', 
    '드라마,가족,판타지',
    '2026-04-15', 
    0,
    '"가끔 지칠 때도 있지만, 저는 잘 지내요" 13살이 된 초보 마녀 키키는 마녀의 전통에 따라 검은 고양이 지지와 함께 낯선 바닷가 마을로 떠난다.',
    102,
    '/resources/img/movies/Kikis_Delivery_Service.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '내 이름은', 
    '정지영', 
    '드라마',
    '2026-04-15', 
    0,
    '지독하게 아픈 봄이었수다, 우리 어멍의 1949년은” 가슴에 묻은 78년의 약속, 이제야 부릅니다. 가장 아픈 비밀에서 가장 찬란한 진실이 된 ‘내 이름은',
    113,
    '/resources/img/movies/My_Name.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '침묵은 친구', 
    '일디코 엔예디', 
    '드라마',
    '2026-04-15', 
    15,
    '독일 대학의 한 식물원에는 1832년부터 인간을 바라보며 뿌리내린 장엄한 한 그루의 은행나무가 서있다.',
    113,
    '/resources/img/movies/Silent_Friend_jsp'
);

commit








