-- 필요 시 테이블 제거
DROP TABLE team_member PURGE;

SELECT * FROM theater;

-- 테이블 생성
-- 회원 테이블
CREATE TABLE final_member (
    num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,		-- 회원번호
    id VARCHAR2(30) UNIQUE NOT NULL,										-- 회원 아이디
    pass VARCHAR2(30) NOT NULL,												-- 비밀번호
    name VARCHAR2(50),														-- 회원이름
    nickname VARCHAR2(30) UNIQUE NOT NULL,									-- 닉네임
    phone VARCHAR2(20),														-- 전화번호
    email VARCHAR2(50),														-- 이메일
    gender VARCHAR2(10),													-- 성별(남성,여성)
    age NUMBER(3)															-- 나이
);

-- 영화 테이블
CREATE TABLE final_movie (
	movie_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 	-- 영화 코드
	title VARCHAR2(150) NOT NULL,												-- 영화 제목
	director VARCHAR2(30) NOT NULL,												-- 감독명
	genre VARCHAR2(50),															-- 장르
	release_date DATE NOT NULL,													-- 개봉일
	age_limit NUMBER(3),														-- 관람연령제한
	story CLOB,																	-- 줄거리
	running_time NUMBER NOT NULL												-- 상영시간(분단위)
	-- 포스터 이미지
);

-- 댓글 테이블
CREATE TABLE movie_comment(
	comment_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 	-- 댓글 번호
	member_id VARCHAR2(30) NOT NULL REFERENCES final_member(id),				-- 회원 아이디
	movie_code NUMBER NOT NULL REFERENCES final_movie(movie_code), 				-- 영화 코드
	content CLOB,																-- 댓글 내용
	score NUMBER NOT NULL,														-- 별점					
	reg_date DATE DEFAULT SYSDATE,												-- 게시 날짜
	update_date DATE															-- 수정 날짜
);

-- 영화관 종류(메가박스, CGV 등)
CREATE TABLE theater(
	theater_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 영화관 코드
	theater_name VARCHAR2(20)													-- 영화관 이름
);

-- 영화관 지점 테이블
CREATE TABLE theater_branch(
	theater_code NUMBER NOT NULL REFERENCES theater(theater_code),				-- 영화관 코드	
	branch_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 지점 코드
	branch_name VARCHAR2(30) NOT NULL,											-- 지점명
	addr VARCHAR2(150) NOT NULL,												-- 주소
	phone VARCHAR2(30)															-- 연락처
);

-- 지점별 상영관 테이블
CREATE TABLE branch_screen(
	branch_code NUMBER NOT NULL REFERENCES theater_branch(branch_code),			-- 지점 코드
	screen_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 상영관 코드
	screen_name VARCHAR2(30) NOT NULL,											-- 상영관 이름(1관 2관 등)
	screen_type VARCHAR2(30) NOT NULL											-- 상영관 종류(2D, 돌비 등)
);

-- 상영관 이름 길이 변경 sql
ALTER TABLE branch_screen MODIFY screen_name VARCHAR2(300);

-- 상영 스케줄 테이블
CREATE TABLE schedule (
	schedule_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	movie_code NUMBER NOT NULL REFERENCES final_movie(movie_code),
	screen_code NUMBER NOT NULL REFERENCES branch_screen(screen_code),
	start_time DATE NOT NULL,
	end_time date
);

ALTER TABLE final_movie ADD poster VARCHAR2(300);

SELECT * FROM final_movie;
SELECT * FROM final_member;

--기존 칼럼 삭제 sql
ALTER TABLE final_movie DROP COLUMN poster;
-- VARCHAR2(300)을 추가하기 전에 CLOB으로 추가하던지 아니면 poster 칼럼을 삭제 후 추가
ALTER TABLE final_movie ADD poster CLOB;
ALTER TABLE final_movie ADD actor VARCHAR2(200);


-- 더미 아이디 추가
INSERT INTO final_member(id, pass, name, nickname, phone, email, gender, age)
SELECT
	-- user1, user2, user3 ... user10000
	'user' || LEVEL AS id,
	
	-- pass1, pass2, pass3 ... pass10000
	'pass' || LEVEL AS pass,
	
	-- 사용자1, 사용자2, 사용자3 ... 사용자10000
	'사용자' || LEVEL AS name,
	
	-- 사용자1, 사용자2, 사용자3 ... 사용자10000
	'사용자' || LEVEL AS nickname,
	
	'01012345678' AS phone,
	
	'email' || LEVEL || '@email.com' AS email,
	
	CASE WHEN MOD(LEVEL, 2) = 1 THEN '남성' ELSE '여성' END AS gender,
	
	-- 나이 (20 ~ 70세 랜덤)
	TRUNC(DBMS_RANDOM.VALUE(20, 70)) AS age
	
FROM DUAL
CONNECT BY LEVEL <= 300;

SELECT count(*) FROM final_member;
SELECT * FROM final_member;

COMMIT


-- 데이터 삽입 (테이블 생성 후 관리자 계정 추가)
INSERT INTO team_member (
    id, pass, name, addr, phone, email, gender, age
) VALUES (
    'admin', 'admin', 'MASTER',
    '부산광역시', '01011111111', 'lkjnibnhjunjh','남성', 30
);

-- 수정
UPDATE team_member 
SET email = 'new_email@example.com'  -- 임시로 넣을 이메일
WHERE id = 'admin';

-- 조회
SELECT * FROM team_member;

-- 커밋
COMMIT


-- ===========================================
-- test_member 테이블에 더미 테이블 추가
-- test_member table 에서 검색 된 결과를
-- test_member 테이블에 그대로 입력
-- id column UNIQUE
-- ORA-00001: 무결성 제약 조건(DEVELOP_JSP.SYS_C008346)에 위배됩니다
-- ===========================================

INSERT INTO team_member(id, pass, name, addr, phone, gender, age)
SELECT id, pass, name, addr, phone, gender, age FROM test_member;

-- ===========================================
-- test_member 테이블에 더미 데이터 10,000건 생성
-- CONNECT BY LEVEL 을 이용한 Oracle 계층 쿼리 활용
-- ===========================================

-- ORA-01722: 수치가 부적합합니다
-- + 연상은 산술(수치형) 연산에서만 사용
SELECT 'a' + 'b' FROM DUAL;

-- 30
SELECT 10 + 20 FROM DUAL;

-- concatenate : 연결하다
-- 'ab'
SELECT concat('a', 'b') FROM DUAL;

-- CONCAT 함수는 인자값 두개만 가능
-- ORA-00909: 인수의 개수가 부적합합니다
-- SELECT concat('a', 'b', 'c') FROM DUAL;
-- 'abc'
SELECT CONCAT(CONCAT('a', 'b'), 'c') FROM DUAL;

-- 'abcd'
SELECT 'a' || 'b' || 'c' || 'd' FROM DUAL;


SELECT
	CASE
		WHEN MOD(3, 2) = 1
			THEN '부산'
			ELSE '서울'
	END		
FROM DUAL;

-- TRUNC() : TRUNCATE : 잘라내다
-- 소수점이나 시간 등을 잘라내는 함수(반올림,내림,올림 아님 : 제거)
SELECT TRUNC(DBMS_RANDOM.VALUE(20, 70)) FROM DUAL;

-- CONNECT BY LEVEL <= 40
-- 1부터 40까지의 자동 증가 숫자 생성
-- SELECT LEVEL FROM DUAL : LEVEL => 계츨 쿼리에서 자동 증하가는 가상 컬럼

SELECT 
	LEVEL
FROM DUAL
CONNECT BY LEVEL <= 40;


-- ============================================

INSERT INTO team_member(id, pass, name, addr, phone, gender, age)
SELECT
	-- user1, user2, user3 ... user10000
	'user' || LEVEL AS id,
	
	-- pass1, pass2, pass3 ... pass10000
	'pass' || LEVEL AS pass,
	
	-- 사용자1, 사용자2, 사용자3 ... 사용자10000
	'사용자' || LEVEL AS name,
	
	CASE WHEN MOD(LEVEL, 2) = 1 THEN '부산' ELSE '서울' END AS addr,
	'01012345678' AS phone,
	CASE WHEN MOD(LEVEL, 2) = 1 THEN '남성' ELSE '여성' END AS gender,
	
	-- 나이 (20 ~ 70세 랜덤)
	TRUNC(DBMS_RANDOM.VALUE(20, 70)) AS age
	
FROM DUAL
CONNECT BY LEVEL <= 10000;

----------------------------------------------------

SELECT count(*) FROM team_member;

COMMIT

-- ============================================
-- 키워드 검색
-- ?searchType=addr&keyword=부산&perPageNum=15
-- ============================================

SELECT * FROM team_member
WHERE id != 'admin' AND addr LIKE '%' || '부산' || '%'
ORDER BY num DESC
OFFSET 0 ROWS FETCH NEXT 25 ROWS ONLY;

-----------------------------------------------------------------------

SELECT count(*) FROM team_member
WHERE id != 'admin' AND addr LIKE '%'||'부산'||'%';
-- WHERE id != 'admin' AND id LIKE '%'||'id'||'%'; -- 0

-- 사용자 이메일 정보 저장을 위찬 column 추가
ALTER TABLE team_member ADD email VARCHAR2(300);

-- 기존 데이터에 DUMMY 이메일 정보 추가
UPDATE team_member
SET email = id || '@gmail.com'
WHERE email IS NULL;

-- NOT NULL 제약 조건 추가 - email 은 비밀번호를 찾기 위한 필수 데이터
ALTER TABLE team_member MODIFY email VARCHAR2(300) NOT NULL;

-- 회원 정보 조회
SELECT * FROM team_member;

-- 게시판 조회
SELECT * FROM board_team;

-- 게시판 더미데이터 삭제
DELETE FROM board_team;

-- 저장
COMMIT

-- 시퀀스 존재 여부 판단
SELECT * FROM user_sequences WHERE sequence_name = 'BOARD_SEQ';
SELECT * FROM user_sequences WHERE sequence_name = 'FINAL_MOVIE_SEQ';

SELECT sequence_name FROM user_sequences;

-- 시퀀스 생성 sql
CREATE SEQUENCE final_movie_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


INSERT INTO board_team(title, author, content, category)
SELECT title, author, content, category
FROM board_team
WHERE category = 'NOTICE';

--필요 시 영화 db 삭제--
DROP TABLE final_movie CASCADE CONSTRAINTS PURGE;

--영화 db 조회--
SELECT * FROM final_movie;

--영화 db 최신 개봉일 순으로 조회
SELECT * FROM final_movie ORDER BY release_date DESC;

--영화 db 포스터 이미지 경로만 수정하는 sql--
UPDATE final_movie 

SET poster = '/resources/img/movies/we_live_in_time.jpg' -- 예시)'/resources/img/movies/we_live_in_time.jpg'



WHERE title = '위 리브 인 타임';

--영화 db등록--
INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time)
VALUES (
    '프로젝트 헤일메리', 
    '필 로드, 크리스 밀러', 
    'sf', 
    '2026-04-18', 
    12,
    '"죽어가는 태양, 종말 위기에 놓인 지구. 인류의 운명을 건 단 하나의 미션. 그의 마지막 임무가 시작된다!"',
    156
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '기동전사 건담 철혈의 오펀스 우르드 헌트', 
    '나가이 타츠유키', 
    'sf', 
    '2026-04-04', 
    12,
    '“축하드립니다. 당신은 ‘우르드 헌트’의 참가 자격을 얻었습니다.” 
    화성과의 개척 경쟁에서 패배하고 죄인들의 유배지로 전락한 변방 행성, 
    금성. 그곳의 라도니차 콜로니에서 나고 자란 소년 위스타리오 아팜은 척박한 고향의 현실을 바꾸고 싶다는 열망을 품고 살아간다.',
    78,
    '/resources/img/movies/gundam.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '런닝맨 라이트&쉐도우', 
    '윤준상', 
    '?', 
    '2026-04-11', 
    0,
    '세상을 지키던 히어로가 다크 런닝맨이 되었다?! 수차례에 걸쳐 세상을 구한 런닝맨들은 트리시티의 대스타로 절대적인 지지를 받고 있다. 
    그러던 어느 날 런닝맨들이 돌연 위험한 악당이 되어 시민들을 공격하기 시작하는데… ',
    81,
    '/resources/img/movies/runningman.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '로마의 휴일', 
    '윌리엄 와일러', 
    '멜로/로맨스, 드라마, 코미디', 
    '2026-04-08', 
    12,
    '유럽 순방 중 로마를 방문한 공주 ‘앤’. 
    끝없는 일정에 지쳐버린 그녀는 한밤중 몰래 침실을 빠져나와 처음으로 자유롭게 로마의 거리를 거닌다.',
    118,
    '/resources/img/movies/roman_holiday.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '티파니에서 아침을', 
    '블레이크 에드워즈', 
    '멜로/로맨스,드라마', 
    '2026-04-08', 
    12,
    '뉴욕 맨해튼에서 자유로운 삶을 살아가는 여성 ‘홀리 골라이틀리’(오드리 헵번)는 화려한 사교 생활을 즐기며 부유한 삶을 동경한다.',
    115,
    '/resources/img/movies/tiffanys.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '리바운드', 
    '장항준', 
    '드라마', 
    '2026-04-05', 
    12,
    '농구선수 출신 공익근무요원 양현은 해체 위기에 놓인 부산중앙고 농구부의 신임 코치로 발탁된다.',
    122,
    '/resources/img/movies/rebound.jpg'
);

DELETE FROM final_movie 
WHERE title = '리바운드';

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (

    '크라임101', 
    '바트 레이튼', 
    '범죄,드라마,스릴러', 
    '2026-04-08', 
    12,
    '흔적도, 증거도 없다! 101번 국도를 따라 흔적도 없이 사라지는 보석들. 전설적인 절도범 ‘데이비스’(크리스 헴스워스)는 자신만의 규칙 아래 완벽한 범죄를 설계한다.',
    140,
    '/resources/img/movies/Crime_101.jpg'
    
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '살목지', 
    '이상민', 
    '공포,스릴러', 
    '2026-04-08', 
    15,
    '기이한 소문이 끊이지 않는 저수지 살목지의 로드뷰 화면에 촬영한 적 없는 정체불명의 형체가 포착된다.
     오늘 안에 반드시 재촬영을 끝내야 하는 상황 속에 살목지로 향한 PD ‘수인’(김혜윤)과 촬영팀.',
    140,
    '/resources/img/movies/Whispering_Water.jpg'
     
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '그대들은 어떻게 살것인가', 
    '미야자키 하야오', 
    '다큐멘터리', 
    '2026-04-15', 
    12,
    '인생이 담긴 마지막 작품을 완성하기 위한 미야자키 하야오의 고뇌와 갈등, 긴 세월을 함께한 동료들과 예기치 못한 이별까지…',
    120,
    '/resources/img/movies/Hayao_Miyazaki_and_the_Heron.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '하이큐 쓰레기장의 결전', 
    '미츠나가 스스무', 
    '스포츠', 
    '2026-04-15', 
    0,
    '봄철 고교 배구대회 1회전과 2회전에서 우승 후보를 차례로 꺾은 카라스노 고등학교는 마침내 3회전에서 인연의 라이벌 네코마 고등학교와 맞붙게 된다.',
    85,
    '/resources/img/movies/High_Q.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '네가 마지막으로 남긴 노래', 
    '미키 타카히로', 
    '멜로, 로맨스',
    '2026-04-11', 
    0,
    '"나에게 가사를 써줄래?” 유난히 눈에 띄지 않는 소년 ‘하루토’와 유난히 빛나는 소녀 ‘아야네’. ',
    102,
    '/resources/img/movies/Kikis_Delivery_Service.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time, poster)
VALUES (
    '짱구', 
    '정우', 
    '드라마',
    '2026-04-22', 
    0,
    '"99번째 오디션 낙방! 자빠져도 다시 한번!" 배우가 되고 싶어 서울 자취러가 된 부산 사나이 짱구. 
     전기세도 못 낼 만큼 팍팍한 서울살이 속에서 되는 일은 좀처럼 없다.',
    95,
    '/resources/img/movies/My_Name.jpg'
);

INSERT INTO final_movie (title, director, genre, release_date, age_limit, story, running_time)
VALUES (
    '쉘터', 
    '릭 로먼워', 
    '액션,스릴러',
    '2026-04-15', 
    15,
    '등대에 홀로 숨어살던 한 남자. 그 앞에 홀로 나타난 한 소녀. 이제 소녀를 지키기 위해, 그 남자의 숨겨왔던 액션 본능이 깨어난다!',
    107
);

DELETE FROM final_movie 
WHERE title = '쉘터' 
AND director = '릭 로먼워';

commit

INSERT INTO theater(theater_name) VALUES('CGV');
INSERT INTO theater(theater_name) VALUES('LOTTE CINEMA');
INSERT INTO theater(theater_name) VALUES('MEGABOX');

SELECT * FROM theater;

-- 영화관 지점 테이블
CREATE TABLE theater_branch(
	theater_code NUMBER NOT NULL REFERENCES theater(theater_code),				-- 영화관 코드	
	branch_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 지점 코드
	branch_name VARCHAR2(30) NOT NULL,											-- 지점명
	addr VARCHAR2(150) NOT NULL,												-- 주소
	phone VARCHAR2(30)															-- 연락처
);
-- branch_name 컬럼의 크기를 100바이트로 확장
ALTER TABLE THEATER_BRANCH 
MODIFY branch_name VARCHAR2(100);
-- theater_branch 테이블 중에 theater_code가 1인 행을 전부 삭제(주의!)
DELETE FROM THEATER_BRANCH WHERE theater_code = 1 AND branch_name = '서면';

-- theater_branch 테이블 중에 theater_code가 3이면서 branch_name이 서면인 행의 branch_code를 1로 수정(추천)
UPDATE THEATER_BRANCH
SET branch_code = 1
WHERE branch_code = 3 AND branch_name = '서면';

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(1, '서면', '부산광역시 부산진구 동천로 4');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(1, '아시아드', '부산광역시 연제구 종합운동장로 7 부산아시아드주경기장 노외주차장');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(1, '신세계백화점 센텀시티점', '부산광역시 해운대구 센텀남대로 35 7,8층');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(1, '대연', '부산광역시 남구 수영로 305 스파크');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(1, '서면삼정타워', '부산광역시 부산진구 중앙대로 672 서면피에스타 11층(부전동)');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(1, '동래', '부산광역시 동래구 중앙대로 1523 SK HUB SKY');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(1, '해운대', '부산광역시 해운대구 해운대로 620 해운대 라뮤에뜨 2층');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(1, '서면상상마당', '부산광역시 부산진구 서면로 39 8층');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(2, '광복점', '부산광역시 중구 중앙대로 2 롯데백화점광복점');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(2, '부산본점', '부산광역시 부산진구 가야대로 772 , 10층');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(2, '센텀시티', '부산광역시 해운대구 센텀남대로 59 롯데백화점');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(2, '동래', '부산광역시 동래구 중앙대로 1393 롯데시네마 8층');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(2, '오투', '부산광역시 금정구 중앙대로 1607');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(2, '부산장림', '부산광역시 사하구 장림번영로 97 더 세븐 6층 롯데시네마');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(3, '사상', '산광역시 사상구 사상로 201 애플아울렛 본관동 4~5층');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(3, '부산대', '부산광역시 금정구 장전로12번길 55 라퓨타아일랜드 4층');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(3, '덕천', '부산광역시 북구 만덕대로 23');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(3, '해운대장산점', '부산광역시 해운대구 해운대로 813 8층');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(3, '부산극장본관', '부산광역시 중구 비프광장로 36'); 22

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(3, '서면대한점', '부산광역시 진구 중앙대로692번길 16 3층');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(3, '화명점', '부산광역시 북구 화명대로 16 7. 8. 9층');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(3, '장산점', '부산광역시 해운대구 해운대로 813 NC백화점해운대점9F');

INSERT INTO THEATER_BRANCH(theater_code, branch_name, addr)
VALUES(26, '부산극장신관', '부산광역시 중구 비프광장로 28'); 

DELETE FROM theater_branch WHERE branch_code =26;



-- 커밋
COMMIT
-- teater_branch 테이블 전체 조회
SELECT * FROM theater_branch;

-- 지점별 상영관 테이블
CREATE TABLE branch_screen(
	branch_code NUMBER NOT NULL REFERENCES theater_branch(branch_code),			-- 지점 코드
	screen_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 상영관 코드
	screen_name VARCHAR2(30) NOT NULL,											-- 상영관 이름(1관 2관 등)
	screen_type VARCHAR2(30) NOT NULL											-- 상영관 종류(2D, 돌비 등)
);

--조회
SELECT * FROM branch_screen;
--삭제
DROP TABLE branch_screen CASCADE CONSTRAINTS;

--branch_screen 데이터 삽입
INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (1, '3관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (1, '4관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (1, '6관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (1, '7관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (1, '9관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (1, 'SCREENX관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (1, 'IMAX관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (1, 'ART1관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (1, 'ART2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (1, '4DX관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (5, '1관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (5, '2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (5, '4관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (5, '5관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (5, '6관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (5, '7관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (5, '4DX관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (27, '2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (27, '4관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (27, '5관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (27, '6관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (27, '7관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (27, '4DX관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (27, 'IMAX관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (7, '1관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (7, '2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (7, '3관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (7, '4관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (7, '5관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (7, '6관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (7, '7관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (7, '8관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (8, '1관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (8, '2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (8, '3관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (8, '4관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (8, '5관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (8, '6관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (8, '7관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (8, '8관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (9, '1관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (9, '2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (9, '3관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (9, '4관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (9, '5관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (9, '6관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (9, '7관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (9, '8관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (9, '9관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (10, '1관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (10, '2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (10, '3관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (10, '4관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (10, '5관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (10, '6관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (11, '1관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (11, '2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (11, '4관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (11, '5관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (11, '6관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (11, 'PRIVATE BOX관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (12, '1관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (12, '2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (12, '3관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (12, '4관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (12, '5관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (12, '6관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (12, '10관 아르떼', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (12, '7관 수퍼 4D', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (12, '9관 수퍼 플렉스 Dolby', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (12, '11관 샤롯데', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (13, '1관 리클라이너', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (13, '2관 리클라이너', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (13, '3관 리클라이너', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (13, '4관 리클라이너', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (13, '6관 리클라이너', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (13, '7관 리클라이너', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (13, '11관 리클라이너', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (13, '5관 광음시네마', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (14, '2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (14, '4관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (14, '5관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (14, '6관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (14, '7관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (14, '10관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (14, '샤롯데', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (14, '8관 아르떼', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (14, '3관 슈퍼 LED', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (15, '2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (15, '3관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (15, '5관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (15, '6관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (15, '7관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (15, '8관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (15, '9관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (15, '1관 소파석', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (15, '4관 광음시네마', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (16, '1관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (16, '2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (16, '3관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (16, '4관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (16, '아르떼', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (17, '1관 리클라이너(레이저영사기)', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (17, '2관 리클라이너(레이저영사기)', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (17, '3관 리클라이너(레이저영사기)', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (17, '4관 리클라이너(레이저영사기)', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (17, '5관 리클라이너(레이저영사기)', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (17, '6관 리클라이너(레이저영사기)', '2D');
  ------------ 메가박스 2026 04 06 --------------
INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (18, '컴포트 1관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (18, '컴포트 2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (18, '컴포트 6관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (18, '컴포트 7관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (19, '2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (19, '7관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (19, '리클라이너 1관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (19, '리클라이너 3관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (19, '리클라이너 4관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (19, '리클라이너 5관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (19, '리클라이너 6관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (20, '컴포트 2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (20, '컴포트 3관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (20, '컴포트 4관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (20, '컴포트 6관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (20, '컴포트 7관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (20, '컴포트 8관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (20, '컴포트 9관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (20, '1관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (21, '리클라이너 1관 ', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (21, '리클라이너 2관 ', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (21, '리클라이너 3관 ', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (21, '리클라이너 4관 ', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (21, '리클라이너 5관 ', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (21, '리클라이너 6관 ', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (21, '리클라이너 7관 ', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (22, '1관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (22, '2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (22, '3관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (22, '4관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (23, '리클라이너 1관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (23, '리클라이너 2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (23, '리클라이너 3관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (24, '리클라이너 1관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (24, '리클라이너 2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (24, '리클라이너 3관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (24, '리클라이너 4관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (24, '리클라이너 5관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (24, '리클라이너 6관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (24, '리클라이너 7관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (26, '1관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (26, '2관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (26, '3관', '2D');

INSERT INTO branch_screen (branch_code, screen_name, screen_type) 
VALUES (26, '4관', '2D');

COMMIT




CREATE TABLE schedule (
	schedule_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	movie_code NUMBER NOT NULL REFERENCES final_movie(movie_code),
	screen_code NUMBER NOT NULL REFERENCES branch_screen(screen_code),
	start_time DATE NOT NULL,
	end_time date
);

SELECT * FROM BRANCH_SCREEN;

SELECT * FROM FINAL_MOVIE;

SELECT * FROM schedule;

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(12, 4, TO_DATE('2026-04-15 13:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(12, 4, TO_DATE('2026-04-15 15:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(12, 4, TO_DATE('2026-04-15 18:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(12, 4, TO_DATE('2026-04-15 20:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 3, TO_DATE('2026-04-15 12:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 3, TO_DATE('2026-04-15 17:15', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 4, TO_DATE('2026-04-16 13:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 4, TO_DATE('2026-04-16 15:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 4, TO_DATE('2026-04-16 18:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 4, TO_DATE('2026-04-16 20:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 3, TO_DATE('2026-04-16 12:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 3, TO_DATE('2026-04-16 17:15', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 3, TO_DATE('2026-04-16 17:15', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 4, TO_DATE('2026-04-17 13:30', 'YYYY-MM-DD HH24:MI'));

DELETE FROM schedule 
WHERE movie_code = 45 
  AND screen_code = 3 
  AND start_time = TO_DATE('2026-04-17 17:15', 'YYYY-MM-DD HH24:MI');
  
DELETE FROM schedule 
WHERE movie_code = 45 
  AND screen_code = 5
  AND start_time = TO_DATE('2026-04-17 15:35', 'YYYY-MM-DD HH24:MI');
  
SELECT * FROM schedule 
WHERE movie_code = 45 
  AND screen_code = 5
  AND start_time = TO_DATE('2026-04-17 17:40', 'YYYY-MM-DD HH24:MI');  

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 4, TO_DATE('2026-04-17 15:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 4, TO_DATE('2026-04-17 18:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 4, TO_DATE('2026-04-17 20:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 3, TO_DATE('2026-04-17 12:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 3, TO_DATE('2026-04-17 17:15', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 4, TO_DATE('2026-04-18 14:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 4, TO_DATE('2026-04-18 17:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 4, TO_DATE('2026-04-18 19:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 4, TO_DATE('2026-04-18 21:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 16, TO_DATE('2026-04-19 14:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 16, TO_DATE('2026-04-19 17:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 16, TO_DATE('2026-04-19 19:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 16, TO_DATE('2026-04-19 21:50', 'YYYY-MM-DD HH24:MI'));



-- schedule 테이블 schedule_code 선택 삭제
DELETE FROM schedule
WHERE schedule_code IN (37, 38, 39, 40);

UPDATE SCHEDULE SET SCREEN_CODE = 5 WHERE SCHEDULE_CODE = 34;

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 3, TO_DATE('2026-04-18 15:25', 'YYYY-MM-DD HH24:MI'));

SELECT * FROM schedule;




INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 3, TO_DATE('2026-04-18 15:25', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 3, TO_DATE('2026-04-18 15:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 5, TO_DATE('2026-04-18 17:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 4, TO_DATE('2026-04-19 14:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 4, TO_DATE('2026-04-19 17:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 4, TO_DATE('2026-04-19 19:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 3, TO_DATE('2026-04-19 12:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 3, TO_DATE('2026-04-19 17:20', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 3, TO_DATE('2026-04-19 17:20', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(12, 4, TO_DATE('2026-04-19 14:50', 'YYYY-MM-DD HH24:MI'));

DELETE FROM schedule
WHERE movie_code = 12
  AND screen_code = 4
  AND start_time = TO_DATE('2026-04-19 14:50', 'YYYY-MM-DD HH24:MI');

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(12, 4, TO_DATE('2026-04-19 17:10', 'YYYY-MM-DD HH24:MI'));

DELETE FROM schedule
WHERE movie_code = 12
  AND screen_code = 4
  AND start_time = TO_DATE('2026-04-19 17:10', 'YYYY-MM-DD HH24:MI');

DELETE FROM schedule
WHERE movie_code = 12
  AND start_time = TO_DATE('2026-04-19 17:10', 'YYYY-MM-DD HH24:MI');

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(12, 4, TO_DATE('2026-04-19 19:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(12, 4, TO_DATE('2026-04-19 21:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(12, 3, TO_DATE('2026-04-19 12:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 3, TO_DATE('2026-04-19 12:40', 'YYYY-MM-DD HH24:MI'));

SELECT ROWID, movie_code, screen_code, start_time
FROM schedule
WHERE movie_code = 12 
  AND screen_code = 3 
  AND start_time = TO_DATE('2026-04-19 12:40', 'YYYY-MM-DD HH24:MI');

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 3, TO_DATE('2026-04-16 17:20', 'YYYY-MM-DD HH24:MI'));

SELECT * FROM schedule;
SELECT * FROM final_movie;

SELECT * FROM BRANCH_SCREEN WHERE branch_code = 22;

SELECT * FROM theater_branch;

DELETE FROM THEATER_BRANCH WHERE branch_code = 26;
DELETE FROM branch_screen WHERE branch_code = 26;

UPDATE THEATER_BRANCH SET branch_name = '부산극장' WHERE branch_code = 22;

UPDATE final_movie SET genre = '애니메이션' WHERE movie_code = 3;

SELECT * FROM FINAL_MOVIE;

SELECT * FROM schedule;


INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(12, 75, TO_DATE('2026-04-15 16:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(9, 74, TO_DATE('2026-04-15 16:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(12, 75, TO_DATE('2026-04-16 18:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(9, 73, TO_DATE('2026-04-17 17:55', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(12, 75, TO_DATE('2026-04-17 18:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(9, 74, TO_DATE('2026-04-17 19:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(46, 74, TO_DATE('2026-04-17 19:10', 'YYYY-MM-DD HH24:MI'));

DELETE FROM schedule
WHERE movie_code = 46
  AND screen_code = 74
  AND start_time = TO_DATE('2026-04-17 19:10', 'YYYY-MM-DD HH24:MI')
  AND ROWNUM = 1;

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(46, 73, TO_DATE('2026-04-17 17:55', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(46, 76, TO_DATE('2026-04-17 19:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(46, 74, TO_DATE('2026-04-17 20:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 75, TO_DATE('2026-04-18 18:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 72, TO_DATE('2026-04-18 20:15', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(46, 73, TO_DATE('2026-04-19 17:55', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(46, 76, TO_DATE('2026-04-19 19:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(46, 74, TO_DATE('2026-04-19 20:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 75, TO_DATE('2026-04-17 17:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 77, TO_DATE('2026-04-17 19:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 75, TO_DATE('2026-04-17 20:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 75, TO_DATE('2026-04-19 17:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 77, TO_DATE('2026-04-19 19:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 75, TO_DATE('2026-04-19 20:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 75, TO_DATE('2026-04-20 17:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 77, TO_DATE('2026-04-20 19:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 75, TO_DATE('2026-04-20 20:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(46, 72, TO_DATE('2026-04-19 19:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(46, 74, TO_DATE('2026-04-19 20:15', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(46, 72, TO_DATE('2026-04-19 21:25', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(46, 72, TO_DATE('2026-04-20 19:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(46, 74, TO_DATE('2026-04-20 20:15', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(46, 72, TO_DATE('2026-04-20 21:25', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(46, 72, TO_DATE('2026-04-21 19:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(46, 74, TO_DATE('2026-04-21 20:15', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(46, 72, TO_DATE('2026-04-21 21:25', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
<<<<<<< HEAD
VALUES(12, 143, TO_DATE('2026-04-11 16:30', 'YYYY-MM-DD HH24:MI'));

select * from theater_branch;
DELETE FROM theater_branch WHERE branch_code = 26;


select * from branch_screen where branch_code = 26; 

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(12, 143, TO_DATE('2026-04-16 16:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(9, 142, TO_DATE('2026-04-13 16:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(9, 142, TO_DATE('2026-04-16 16:50', 'YYYY-MM-DD HH24:MI'));
=======
VALUES(8, 83, TO_DATE('2026-04-15 16:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 83, TO_DATE('2026-04-15 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 83, TO_DATE('2026-04-15 20:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 83, TO_DATE('2026-04-16 16:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 83, TO_DATE('2026-04-16 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 83, TO_DATE('2026-04-16 20:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 83, TO_DATE('2026-04-17 16:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 83, TO_DATE('2026-04-17 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 83, TO_DATE('2026-04-17 20:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 83, TO_DATE('2026-04-18 16:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 83, TO_DATE('2026-04-18 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 83, TO_DATE('2026-04-18 20:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 83, TO_DATE('2026-04-19 16:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 83, TO_DATE('2026-04-19 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 83, TO_DATE('2026-04-19 20:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 83, TO_DATE('2026-04-20 16:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 83, TO_DATE('2026-04-20 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 83, TO_DATE('2026-04-20 20:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 75, TO_DATE('2026-04-16 16:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 74, TO_DATE('2026-04-16 17:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 75, TO_DATE('2026-04-16 18:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 74, TO_DATE('2026-04-16 20:00', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 75, TO_DATE('2026-04-16 21:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 75, TO_DATE('2026-04-17 16:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 74, TO_DATE('2026-04-17 17:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 75, TO_DATE('2026-04-17 18:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 74, TO_DATE('2026-04-17 20:00', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 75, TO_DATE('2026-04-17 21:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 75, TO_DATE('2026-04-18 16:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 74, TO_DATE('2026-04-18 17:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 75, TO_DATE('2026-04-18 18:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 74, TO_DATE('2026-04-18 20:00', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 75, TO_DATE('2026-04-18 21:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 75, TO_DATE('2026-04-20 16:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 74, TO_DATE('2026-04-20 17:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 75, TO_DATE('2026-04-20 18:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 74, TO_DATE('2026-04-20 20:00', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 75, TO_DATE('2026-04-20 21:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 75, TO_DATE('2026-04-21 16:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 74, TO_DATE('2026-04-21 17:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 75, TO_DATE('2026-04-21 18:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 74, TO_DATE('2026-04-21 20:00', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 75, TO_DATE('2026-04-21 21:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(7, 72, TO_DATE('2026-04-17 17:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(7, 72, TO_DATE('2026-04-17 21:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(7, 72, TO_DATE('2026-04-20 17:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(7, 72, TO_DATE('2026-04-20 21:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 76, TO_DATE('2026-04-16 16:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 76, TO_DATE('2026-04-16 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 76, TO_DATE('2026-04-16 20:35', 'YYYY-MM-DD HH24:MI'));
>>>>>>> 7eeb187b844bd70c1d02dde12e8f83f7f38bba63

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(11, 14, TO_DATE('2026-04-16 13:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
<<<<<<< HEAD
VALUES(4, 12, TO_DATE('2026-04-09 21:15', 'YYYY-MM-DD HH24:MI'));
=======
VALUES(8, 76, TO_DATE('2026-04-17 16:45', 'YYYY-MM-DD HH24:MI'));

DELETE FROM schedule
WHERE movie_code = 8
  AND screen_code = 76
  AND start_time = TO_DATE('2026-04-17 16:45', 'YYYY-MM-DD HH24:MI');

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 76, TO_DATE('2026-04-17 20:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 76, TO_DATE('2026-04-18 16:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 76, TO_DATE('2026-04-18 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 76, TO_DATE('2026-04-18 20:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 76, TO_DATE('2026-04-19 16:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 76, TO_DATE('2026-04-19 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 76, TO_DATE('2026-04-19 20:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 76, TO_DATE('2026-04-20 16:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 76, TO_DATE('2026-04-20 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 76, TO_DATE('2026-04-20 20:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 76, TO_DATE('2026-04-21 16:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 76, TO_DATE('2026-04-21 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 76, TO_DATE('2026-04-21 20:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 77, TO_DATE('2026-04-15 12:00', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 77, TO_DATE('2026-04-15 16:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 77, TO_DATE('2026-04-16 12:00', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 77, TO_DATE('2026-04-16 16:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 77, TO_DATE('2026-04-17 12:00', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 77, TO_DATE('2026-04-17 16:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 77, TO_DATE('2026-04-18 12:00', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 77, TO_DATE('2026-04-19 12:00', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(45, 77, TO_DATE('2026-04-19 16:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(44, 75, TO_DATE('2026-04-18 17:05', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(44, 76, TO_DATE('2026-04-18 17:15', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(44, 76, TO_DATE('2026-04-18 19:30', 'YYYY-MM-DD HH24:MI'));

SELECT * FROM schedule;
>>>>>>> 7eeb187b844bd70c1d02dde12e8f83f7f38bba63

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(5, 12, TO_DATE('2026-04-09 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(4, 12, TO_DATE('2026-04-10 21:15', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(5, 12, TO_DATE('2026-04-10 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(4, 11, TO_DATE('2026-04-11 15:40', 'YYYY-MM-DD HH24:MI'));

DELETE FROM schedule 
WHERE movie_code = 4 
  AND screen_code = 12 
  AND start_time = TO_DATE('2026-04-11 21:15', 'YYYY-MM-DD HH24:MI');

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(5, 11, TO_DATE('2026-04-11 18:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(4, 32, TO_DATE('2026-04-12 16:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(5, 5, TO_DATE('2026-04-12 21:00', 'YYYY-MM-DD HH24:MI'));

DELETE FROM schedule 
WHERE movie_code = 5 
  AND screen_code = 11 
  AND start_time = TO_DATE('2026-04-12 21:00', 'YYYY-MM-DD HH24:MI');
  
INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(11, 14, TO_DATE('2026-04-15 13:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(11, 14, TO_DATE('2026-04-16 13:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 79, TO_DATE('2026-04-12 10:00', 'YYYY-MM-DD HH24:MI'));

DELETE FROM schedule 
WHERE movie_code = 8 
  AND screen_code = 79 
  AND start_time = TO_DATE('2026-04-12 13:40', 'YYYY-MM-DD HH24:MI');

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 79, TO_DATE('2026-04-12 12:05', 'YYYY-MM-DD HH24:MI'));

DELETE FROM schedule 
WHERE movie_code = 8 
  AND screen_code = 79 
  AND start_time = TO_DATE('2026-04-12 15:45', 'YYYY-MM-DD HH24:MI');

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 79, TO_DATE('2026-04-12 14:10', 'YYYY-MM-DD HH24:MI'));

DELETE FROM schedule 
WHERE movie_code = 8 
  AND screen_code = 79 
  AND start_time = TO_DATE('2026-04-12 17:50', 'YYYY-MM-DD HH24:MI');
  
INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 79, TO_DATE('2026-04-12 16:15', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 79, TO_DATE('2026-04-12 18:20', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 79, TO_DATE('2026-04-12 20:25', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 79, TO_DATE('2026-04-12 22:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(11, 74, TO_DATE('2026-04-15 14:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(11, 74, TO_DATE('2026-04-15 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(11, 74, TO_DATE('2026-04-16 14:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(11, 74, TO_DATE('2026-04-16 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(11, 74, TO_DATE('2026-04-17 14:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(11, 74, TO_DATE('2026-04-17 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(43, 14, TO_DATE('2026-04-17 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(9, 74, TO_DATE('2026-04-13 16:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(9, 74, TO_DATE('2026-04-14 16:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(9, 74, TO_DATE('2026-04-16 16:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 107, TO_DATE('2026-04-13 10:20', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 107, TO_DATE('2026-04-13 14:25', 'YYYY-MM-DD HH24:MI'));

-- schedule 테이블에서 영화코드가 8 이면서 극장코드가 107 인 행을 조회하는 sql
SELECT * FROM schedule WHERE movie_code = 8 AND screen_code = 107;
-- schedule 테이블에서 스케쥴코드가 204 인 행을 조회하는 sql
SELECT * FROM schedule WHERE schedule_code IN(204,...);
-- schedule 테이블에서 스케쥴코드가 202에서 203 사이의 모든 행을 삭제하는 sql
DELETE FROM schedule WHERE schedule_code BETWEEN 202 AND 203;
-- schedule 테이블의 해당 schedule_code의 start_time 값을 수정하는 sql
UPDATE schedule 
SET start_time = TO_DATE('2026-04-13 10:20', 'YYYY-MM-DD HH24:MI')
WHERE schedule_code=204;

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 107, TO_DATE('2026-04-13 18:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 107, TO_DATE('2026-04-13 20:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 109, TO_DATE('2026-04-13 9:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 109, TO_DATE('2026-04-13 11:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 109, TO_DATE('2026-04-13 13:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 109, TO_DATE('2026-04-13 15:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 109, TO_DATE('2026-04-13 17:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 109, TO_DATE('2026-04-13 19:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 109, TO_DATE('2026-04-13 21:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 106, TO_DATE('2026-04-13 10:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 106, TO_DATE('2026-04-13 13:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 106, TO_DATE('2026-04-13 20:55', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 111, TO_DATE('2026-04-13 9:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 111, TO_DATE('2026-04-13 12:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 111, TO_DATE('2026-04-13 15:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 111, TO_DATE('2026-04-13 18:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 108, TO_DATE('2026-04-13 9:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 108, TO_DATE('2026-04-13 11:55', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 108, TO_DATE('2026-04-13 14:20', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 108, TO_DATE('2026-04-13 16:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 108, TO_DATE('2026-04-13 19:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 108, TO_DATE('2026-04-13 21:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 110, TO_DATE('2026-04-13 10:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 110, TO_DATE('2026-04-13 15:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 110, TO_DATE('2026-04-13 17:55', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(43, 110, TO_DATE('2026-04-13 13:05', 'YYYY-MM-DD HH24:MI'));

DELETE FROM schedule 
WHERE movie_code = 43 
  AND screen_code = 191 
  AND start_time = TO_DATE('2026-04-13 13:05', 'YYYY-MM-DD HH24:MI');

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(43, 110, TO_DATE('2026-04-14 13:05', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 107, TO_DATE('2026-04-14 10:20', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 107, TO_DATE('2026-04-14 14:25', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 107, TO_DATE('2026-04-14 18:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 107, TO_DATE('2026-04-14 20:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 109, TO_DATE('2026-04-14 9:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 109, TO_DATE('2026-04-14 11:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 109, TO_DATE('2026-04-14 13:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 109, TO_DATE('2026-04-14 15:30', 'YYYY-MM-DD HH24:MI'));

DELETE FROM schedule 
WHERE movie_code = 8 
  AND screen_code = 109 
  AND start_time = TO_DATE('2026-04-14 13:30', 'YYYY-MM-DD HH24:MI');
  
INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 109, TO_DATE('2026-04-14 17:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 109, TO_DATE('2026-04-14 19:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 109, TO_DATE('2026-04-14 21:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 106, TO_DATE('2026-04-14 10:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 106, TO_DATE('2026-04-14 13:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 106, TO_DATE('2026-04-14 20:55', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 111, TO_DATE('2026-04-14 9:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 111, TO_DATE('2026-04-14 12:35', 'YYYY-MM-DD HH24:MI'));

DELETE FROM schedule 
WHERE movie_code = 47 
  AND screen_code = 111 
  AND start_time = TO_DATE('2026-04-14 11:55', 'YYYY-MM-DD HH24:MI');

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 111, TO_DATE('2026-04-14 15:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 111, TO_DATE('2026-04-14 18:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 108, TO_DATE('2026-04-14 9:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 108, TO_DATE('2026-04-14 11:55', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 108, TO_DATE('2026-04-14 14:20', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 108, TO_DATE('2026-04-14 16:45', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 108, TO_DATE('2026-04-14 19:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 110, TO_DATE('2026-04-14 10:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 110, TO_DATE('2026-04-14 15:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 110, TO_DATE('2026-04-14 17:55', 'YYYY-MM-DD HH24:MI'));

SELECT * FROM THEATER_BRANCH;

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 130, TO_DATE('2026-04-17 17:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 131, TO_DATE('2026-04-17 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 130, TO_DATE('2026-04-17 19:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 131, TO_DATE('2026-04-17 20:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 130, TO_DATE('2026-04-17 21:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 130, TO_DATE('2026-04-18 17:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 131, TO_DATE('2026-04-18 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 130, TO_DATE('2026-04-18 19:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 131, TO_DATE('2026-04-18 20:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 130, TO_DATE('2026-04-18 21:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 130, TO_DATE('2026-04-19 17:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 131, TO_DATE('2026-04-19 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 130, TO_DATE('2026-04-19 19:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 131, TO_DATE('2026-04-19 20:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 130, TO_DATE('2026-04-19 21:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 130, TO_DATE('2026-04-20 17:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 131, TO_DATE('2026-04-20 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 130, TO_DATE('2026-04-20 19:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 131, TO_DATE('2026-04-20 20:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 130, TO_DATE('2026-04-20 21:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 130, TO_DATE('2026-04-21 17:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 131, TO_DATE('2026-04-21 18:40', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 130, TO_DATE('2026-04-21 19:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 131, TO_DATE('2026-04-21 20:35', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(8, 130, TO_DATE('2026-04-21 21:30', 'YYYY-MM-DD HH24:MI'));

SELECT * FROM schedule;
SELECT * FROM final_movie;

SELECT * FROM BRANCH_SCREEN;

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 126, TO_DATE('2026-04-19 19:00', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 125, TO_DATE('2026-04-19 20:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 126, TO_DATE('2026-04-20 19:00', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(47, 125, TO_DATE('2026-04-20 20:30', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(7, 127, TO_DATE('2026-04-20 20:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 129, TO_DATE('2026-04-18 18:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 128, TO_DATE('2026-04-18 20:00', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 129, TO_DATE('2026-04-18 21:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 129, TO_DATE('2026-04-20 18:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 128, TO_DATE('2026-04-20 20:00', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 129, TO_DATE('2026-04-20 21:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 129, TO_DATE('2026-04-21 18:50', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 128, TO_DATE('2026-04-21 20:00', 'YYYY-MM-DD HH24:MI'));

INSERT INTO schedule(movie_code, screen_code, start_time)
VALUES(50, 129, TO_DATE('2026-04-21 21:10', 'YYYY-MM-DD HH24:MI'));

SELECT s.start_time, m.running_time,
       s.start_time + m.running_time/1440 AS end_time
FROM schedule s
JOIN final_movie m ON s.movie_code = m.movie_code
WHERE rownum <= 5;
