-- 필요 시 테이블 제거
DROP TABLE team_member PURGE;

-- 테이블 생성
-- 회원 테이블
CREATE TABLE final_member (
    num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,		-- 회원번호
    id VARCHAR2(30) UNIQUE NOT NULL,										-- 회원 아이디
    pass VARCHAR2(30) NOT NULL,												-- 비밀번호
    name VARCHAR2(50),														-- 회원이름
    nickname VARCHAR2(30) UNIQUE NOT NULL,									-- 닉네임
    phone VARCHAR2(20),														-- 전화번호
    email VARCHAR2(50),														-- 이메일
    gender VARCHAR2(10),													-- 성별(남성,여성)
    age NUMBER(3)															-- 나이
);

-- 영화 테이블
CREATE TABLE final_movie (
	movie_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 	-- 영화 코드
	title VARCHAR2(150) NOT NULL,												-- 영화 제목
	director VARCHAR2(30) NOT NULL,												-- 감독명
	genre VARCHAR2(50),															-- 장르
	release_date DATE NOT NULL,													-- 개봉일
	age_limit NUMBER(3),														-- 관람연령제한
	story CLOB,																	-- 줄거리
	running_time NUMBER NOT NULL												-- 상영시간(분단위)
	-- 포스터 이미지
);

-- 댓글 테이블
CREATE TABLE movie_comment(
	comment_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 	-- 댓글 번호
	member_id VARCHAR2(30) NOT NULL REFERENCES final_member(id),			-- 회원 아이디
	movie_code NUMBER NOT NULL REFERENCES final_movie(movie_code), 				-- 영화 코드
	content CLOB,																-- 댓글 내용
	score NUMBER NOT NULL,														-- 별점					
	reg_date DATE DEFAULT SYSDATE,												-- 게시 날짜
	update_date DATE															-- 수정 날짜
);

-- 영화관 종류(메가박스, CGV 등)
CREATE TABLE theater(
	theater_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 영화관 코드
	theater_name VARCHAR2(20)													-- 영화관 이름
);

-- 영화관 지점 테이블
CREATE TABLE theater_branch(
	theater_code NUMBER NOT NULL REFERENCES theater(theater_code),				-- 영화관 코드	
	branch_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 지점 코드
	branch_name VARCHAR2(30) NOT NULL,											-- 지점명
	addr VARCHAR2(150) NOT NULL,												-- 주소
	phone VARCHAR2(30)															-- 연락처
);

-- 지점별 상영관 테이블
CREATE TABLE branch_screen(
	branch_code NUMBER NOT NULL REFERENCES theater_branch(branch_code),			-- 지점 코드
	screen_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 상영관 코드
	screen_name VARCHAR2(30) NOT NULL,											-- 상영관 이름(1관 2관 등)
	screen_type VARCHAR2(30) NOT NULL											-- 상영관 종류(2D, 돌비 등)
);

CREATE TABLE schedule (
	schedule_code NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	movie_code NUMBER NOT NULL REFERENCES final_movie(movie_code),
	screen_code NUMBER NOT NULL REFERENCES branch_screen(screen_code),
	start_time DATE NOT NULL,
	end_time date
);

ALTER TABLE final_movie ADD poster VARCHAR2(300);

SELECT * FROM final_movie;



-- 데이터 삽입 (테이블 생성 후 관리자 계정 추가)
INSERT INTO team_member (
    id, pass, name, addr, phone, email, gender, age
) VALUES (
    'admin', 'admin', 'MASTER',
    '부산광역시', '01011111111', 'lkjnibnhjunjh','남성', 30
);

-- 수정
UPDATE team_member 
SET email = 'new_email@example.com'  -- 임시로 넣을 이메일
WHERE id = 'admin';

-- 조회
SELECT * FROM team_member;

-- 커밋
COMMIT


-- ===========================================
-- test_member 테이블에 더미 테이블 추가
-- test_member table 에서 검색 된 결과를
-- test_member 테이블에 그대로 입력
-- id column UNIQUE
-- ORA-00001: 무결성 제약 조건(DEVELOP_JSP.SYS_C008346)에 위배됩니다
-- ===========================================

INSERT INTO team_member(id, pass, name, addr, phone, gender, age)
SELECT id, pass, name, addr, phone, gender, age FROM test_member;

-- ===========================================
-- test_member 테이블에 더미 데이터 10,000건 생성
-- CONNECT BY LEVEL 을 이용한 Oracle 계층 쿼리 활용
-- ===========================================

-- ORA-01722: 수치가 부적합합니다
-- + 연상은 산술(수치형) 연산에서만 사용
SELECT 'a' + 'b' FROM DUAL;

-- 30
SELECT 10 + 20 FROM DUAL;

-- concatenate : 연결하다
-- 'ab'
SELECT concat('a', 'b') FROM DUAL;

-- CONCAT 함수는 인자값 두개만 가능
-- ORA-00909: 인수의 개수가 부적합합니다
-- SELECT concat('a', 'b', 'c') FROM DUAL;
-- 'abc'
SELECT CONCAT(CONCAT('a', 'b'), 'c') FROM DUAL;

-- 'abcd'
SELECT 'a' || 'b' || 'c' || 'd' FROM DUAL;


SELECT
	CASE
		WHEN MOD(3, 2) = 1
			THEN '부산'
			ELSE '서울'
	END		
FROM DUAL;

-- TRUNC() : TRUNCATE : 잘라내다
-- 소수점이나 시간 등을 잘라내는 함수(반올림,내림,올림 아님 : 제거)
SELECT TRUNC(DBMS_RANDOM.VALUE(20, 70)) FROM DUAL;

-- CONNECT BY LEVEL <= 40
-- 1부터 40까지의 자동 증가 숫자 생성
-- SELECT LEVEL FROM DUAL : LEVEL => 계츨 쿼리에서 자동 증하가는 가상 컬럼

SELECT 
	LEVEL
FROM DUAL
CONNECT BY LEVEL <= 40;


-- ============================================

INSERT INTO team_member(id, pass, name, addr, phone, gender, age)
SELECT
	-- user1, user2, user3 ... user10000
	'user' || LEVEL AS id,
	
	-- pass1, pass2, pass3 ... pass10000
	'pass' || LEVEL AS pass,
	
	-- 사용자1, 사용자2, 사용자3 ... 사용자10000
	'사용자' || LEVEL AS name,
	
	CASE WHEN MOD(LEVEL, 2) = 1 THEN '부산' ELSE '서울' END AS addr,
	'01012345678' AS phone,
	CASE WHEN MOD(LEVEL, 2) = 1 THEN '남성' ELSE '여성' END AS gender,
	
	-- 나이 (20 ~ 70세 랜덤)
	TRUNC(DBMS_RANDOM.VALUE(20, 70)) AS age
	
FROM DUAL
CONNECT BY LEVEL <= 10000;

----------------------------------------------------

SELECT count(*) FROM team_member;

COMMIT

-- ============================================
-- 키워드 검색
-- ?searchType=addr&keyword=부산&perPageNum=15
-- ============================================

SELECT * FROM team_member
WHERE id != 'admin' AND addr LIKE '%' || '부산' || '%'
ORDER BY num DESC
OFFSET 0 ROWS FETCH NEXT 25 ROWS ONLY;

-----------------------------------------------------------------------

SELECT count(*) FROM team_member
WHERE id != 'admin' AND addr LIKE '%'||'부산'||'%';
-- WHERE id != 'admin' AND id LIKE '%'||'id'||'%'; -- 0

-- 사용자 이메일 정보 저장을 위찬 column 추가
ALTER TABLE team_member ADD email VARCHAR2(300);

-- 기존 데이터에 DUMMY 이메일 정보 추가
UPDATE team_member
SET email = id || '@gmail.com'
WHERE email IS NULL;

-- NOT NULL 제약 조건 추가 - email 은 비밀번호를 찾기 위한 필수 데이터
ALTER TABLE team_member MODIFY email VARCHAR2(300) NOT NULL;

-- 회원 정보 조회
SELECT * FROM team_member;

-- 게시판 조회
SELECT * FROM board_team;

-- 게시판 더미데이터 삭제
DELETE FROM board_team;

-- 저장
COMMIT

-- 시퀀스 존재 여부 판단
SELECT * FROM user_sequences WHERE sequence_name = 'BOARD_SEQ';



INSERT INTO board_team(title, author, content, category)
SELECT title, author, content, category
FROM board_team
WHERE category = 'NOTICE';









